services:
  postgres:
    image: postgres:17-alpine
    container_name: coldchain-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 8
    networks:
      - coldchain-net

  discovery-service:
    build:
      context: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - coldchain-net

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      AUDIT_SERVICE_URL: http://audit-trail-service:8087
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - coldchain-net

  requisition-service:
    build:
      context: ./requisition-service
    container_name: requisition-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/requisition_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      INVENTORY_SERVICE_URL: http://inventory-service:8081
      AUDIT_SERVICE_URL: http://audit-trail-service:8087
      ALERT_SERVICE_URL: http://alert-service:8084
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
      inventory-service:
        condition: service_started
    networks:
      - coldchain-net

  temperature-service:
    build:
      context: ./temperature-service
    container_name: temperature-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/temperature_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      AUDIT_SERVICE_URL: http://audit-trail-service:8087
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - coldchain-net

  alert-service:
    build:
      context: ./alerte-service
    container_name: alert-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alert_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      INVENTORY_SERVICE_URL: http://inventory-service:8081
      TEMPERATURE_SERVICE_URL: http://temperature-service:8083
      AUDIT_SERVICE_URL: http://audit-trail-service:8087
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
      inventory-service:
        condition: service_started
      temperature-service:
        condition: service_started
    networks:
      - coldchain-net

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      AUTH_SERVICE_URL: http://auth-service:8086
      AUDIT_SERVICE_URL: http://audit-trail-service:8087
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
    ports:
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - coldchain-net

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      USER_SERVICE_URL: http://user-service:8085
      AUDIT_SERVICE_URL: http://audit-trail-service:8087
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
    ports:
      - "8086:8086"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
      user-service:
        condition: service_started
    networks:
      - coldchain-net

  audit-trail-service:
    build:
      context: ./audit-trail-service
    container_name: audit-trail-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/audit_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    ports:
      - "8087:8087"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - coldchain-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS: 5
    ports:
      - "8080:8080"
    depends_on:
      discovery-service:
        condition: service_started
      inventory-service:
        condition: service_started
      requisition-service:
        condition: service_started
      temperature-service:
        condition: service_started
      alert-service:
        condition: service_started
      user-service:
        condition: service_started
      auth-service:
        condition: service_started
      audit-trail-service:
        condition: service_started
    networks:
      - coldchain-net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8080
    container_name: coldchain-frontend
    ports:
      - "5173:80"
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - coldchain-net

volumes:
  postgres-data:

networks:
  coldchain-net:
    driver: bridge
